name: Run tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21, 1.22]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Print environment
        run: go env

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v -cover ./...

      - name: Build without CGO
        run: go build -v ./...
        env:
          CGO_ENABLED: 0

      - name: Test without CGO
        run: go test -v ./...
        env:
          CGO_ENABLED: 0

      - name: Test with nosimd tag
        run: go test -v -tags nosimd ./...
